version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt || true
  build:
    commands:
      - echo Build completed successfully.

artifacts:
  files:
    - app.py
