version: 0.2

phases:
  install:
    commands:
      - echo Nothing to install
  build:
    commands:
      - echo Zipping application files
      - zip -r app.zip app.py

artifacts:
  files:
    - app.zip
